### ISSUE TITLE
Update pub.dartlang.org

### ISSUE THREAD

**Issue by ltackmann** [justinfagnani/route#14]
The version hosted on pub.dartlang.org fails on 20193

```
NoSuchMethodError : method not found: 'firstMatching'
Receiver: Instance of '_HashTableKeyIterable@0x23c35ea0<UrlPattern>'
Arguments: [Closure: (dynamic, dynamic) => dynamic]
Stack Trace: #0      Object.noSuchMethod (dart:core-patch:1884:25)
#1      Router._getUrl (http://127.0.0.1:3030/Users/lt/Projects/tackmann.co/web/out/packages/route/client.dart:43:59)
#2      Router.gotoPath (http://127.0.0.1:3030/Users/lt/Projects/tackmann.co/web/out/packages/route/client.dart:111:19)
#3      AppController.go (http://127.0.0.1:3030/Users/lt/Projects/tackmann.co/web/out/app.dart:30:21)
#4      main (http://127.0.0.1:3030/Users/lt/Projects/tackmann.co/web/out/app.dart:19:16)
#5      main (http://127.0.0.1:3030/Users/lt/Projects/tackmann.co/web/out/index.html_bootstrap.dart:8:16)
```

**Comment by justinfagnani** [comment]
Working on it now. The repo has a working version, so you can use a git: dependency, but I'll have it uploaded in a few minutes.

**Comment by ltackmann** [comment]
great

**Comment by justinfagnani** [comment]
Uploaded. Note that I switched versions to match the SDK, if you're using tight version constraints.
