### ISSUE TITLE
No handler found error when running in Dartium

### ISSUE THREAD

**Issue by marcojakob** [justinfagnani/route#31]
I tried to start the provided example application in Dart Editor. It works when I run it as JavaScript but doesn't work in Dartium.

OS: Win7 64bit
Dart SDK: 0.5.1.0_r22072

Error message and log output:

``` text
[FINEST] addHandler /one
[FINEST] addHandler /two
[FINEST] listen ignoreClick=false useFragment=false
[FINEST] onPopState handle(/C:/Users/{user}/dart/routing/web/example.html)
[FINEST] handle /C:/Users//{user}/dart/routing/web/example.html
Exception: Illegal argument(s): No handler found for /C:/Users//{user}/dart/routing/web/example.html
Stack Trace: #0      Router._getUrl (package:route/client.dart:48:7)
#1      Router.handle (package:route/client.dart:66:22)
#2      Router.listen.<anonymous closure> (package:route/client.dart:97:15)

Exception: Illegal argument(s): No handler found for /C:/Users//{user}/dart/routing/web/example.html
Stack Trace: #0      Router._getUrl (package:route/client.dart:48:7)
#1      Router.handle (package:route/client.dart:66:22)
#2      Router.listen.<anonymous closure> (package:route/client.dart:97:15)
```

**Comment by marcojakob** [comment]
Might be the same problem as discussed in [Routes: using fragments](https://groups.google.com/a/dartlang.org/d/msg/misc/Vk3LUXFKplo/pjIvXSAuOWAJ)

Is there a way to make `route` work with Dart Editor?

(Thanks for the great work!)

**Comment by sethladd** [comment]
I think I just ran into this. Using editor + dartium, and route is complaining that it can't find a route for the index.html itself. Which is correct, I never setup a route for home.

**Comment by hatuan** [comment]
Is there anyway to use route with editor + dartium. I am learning dart web ui with multiple views?

**Comment by sethladd** [comment]
Any ideas or progress on this?

**Comment by sethladd** [comment]
Here's the very hacky fix:
https://github.com/dart-lang/route/issues/41
